# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ExtendTransfer_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='import_pct',
        ),
    ]
